"""
Loads prompt text (system prompt, and any templated task prompts) from
the harness/prompts/ directory, so prompt content lives in plain
markdown/text files rather than being embedded as Python string literals.
This keeps prompt iteration decoupled from code changes.
"""

from pathlib import Path

PROMPTS_DIR = Path(__file__).resolve().parent


def load_system_prompt() -> str:
    """Load the project's system prompt (harness/prompts/system_prompt.md).

    This file is generated by scripts/scaffold.py from
    templates/system_prompt.md.template + your project's rapid-prototype
    artifacts (intake/brief.md, architecture.md) — it is NOT meant to be
    edited by hand every time you start a task; edit it once, after
    scaffolding, to reflect your actual project.
    """
    return (PROMPTS_DIR / "system_prompt.md").read_text(encoding="utf-8")


def load_task(name: str) -> str:
    """Load a task/spec prompt by filename (relative to harness/prompts/).

    Example: load_task("task_001_scaffold_backend.md")
    """
    path = PROMPTS_DIR / name
    if not path.exists():
        raise FileNotFoundError(f"No such task prompt: {name!r} (looked in {PROMPTS_DIR})")
    return path.read_text(encoding="utf-8")


def load_app_context() -> str | None:
    """Load app/CONTEXT.md — the durable, agent-maintained project memory
    for the app being built (architecture decisions, current state, etc.).

    Returns None if no CONTEXT.md exists yet (e.g. on a brand-new sandbox
    with nothing built so far) rather than raising, since not having a
    context file yet is a normal, expected state.
    """
    # Import locally to avoid a hard dependency/import-order issue between
    # harness.prompts and harness.tools at module load time.
    from harness.tools.filesystem import SANDBOX_ROOT

    context_path = SANDBOX_ROOT / "CONTEXT.md"
    if not context_path.exists():
        return None
    return context_path.read_text(encoding="utf-8")
